### ISSUE TITLE
Support for Unique keys

### ISSUE THREAD

**Issue by luzlab** [hackolade/CosmosDB-with-SQL-API#1]
CosmosDB provides a mechanism for enforcing uniqueness for keys. Will hackolade support tracking and reporting of unique keys?

<img width="438" alt="image" src="https://user-images.githubusercontent.com/9924835/57561217-4b999100-733f-11e9-9fda-9df20f21d8bf.png">

**Comment by pdesmarets** [comment]
Yes, of course, we'll add that shortly and let you know as soon as the new plugin version is available.

**Comment by pdesmarets** [comment]
Earlier this week, we released a new version of the plugin which now supports unique keys.

**Comment by luzlab** [comment]
Thank you!
